version: '2'

services:
  edgedirectorui:
    image: docker.io/axelst/fooddatabase:0.1
    container_name: fooddatabase
    restart: always
    ports:
      - 8081:80
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "2"
